version: '3.3'

services:
  django_app:
    build:
      context: ./blog
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./blog/db.sqlite3:/app/db.sqlite3
      
  fastapi:
    build:
      context: ./blog
      dockerfile: Dockerfile
    command: uvicorn api:app --reload --host g-nix.tech --port 7000
    ports:
      - "7000:7000"
    volumes:
      - ./blog/db.sqlite3:/app/db.sqlite3
