# Generated by Django 5.0.4 on 2024-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('keywords_header', models.CharField(max_length=300, verbose_name='Keywords Header')),
                ('description_header', models.CharField(max_length=300, verbose_name='Description Header')),
                ('catalog_name', models.CharField(max_length=100, verbose_name='Catalog Name')),
                ('short_description', models.CharField(max_length=400, verbose_name='Short Description')),
                ('full_description', models.CharField(max_length=400, verbose_name='Full Description')),
                ('image', models.ImageField(default='default.png', upload_to='', verbose_name='Image')),
                ('date_added', models.DateField(verbose_name='Date Added')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='CatalogOfArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('keywords_header', models.CharField(max_length=300, verbose_name='Keywords Header')),
                ('description_header', models.CharField(max_length=300, verbose_name='Description Header')),
                ('catalog_name', models.CharField(max_length=100, verbose_name='Catalog Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Catalog of Articles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('last_name', models.CharField(blank=True, default='-', max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(blank=True, default='-', max_length=50, verbose_name='First Name')),
                ('date_birth', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
