# Generated by Django 5.0.4 on 2024-04-18 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='catalogofarticles',
            options={'verbose_name': 'Catalog of Article', 'verbose_name_plural': 'Catalog of Articles'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='blog',
            name='title_catalog',
            field=models.CharField(default=1, max_length=400, verbose_name='Title Catalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogofarticles',
            name='url_catalog',
            field=models.URLField(default='-', max_length=1000, verbose_name='URL Catalog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='catalog_name',
            field=models.TextField(max_length=100, verbose_name='Catalog Name'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_header',
            field=models.TextField(max_length=300, verbose_name='Description Header'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=400, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords_header',
            field=models.TextField(max_length=300, verbose_name='Keywords Header'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=400, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='catalogofarticles',
            name='catalog_name',
            field=models.TextField(max_length=100, verbose_name='Catalog Name'),
        ),
        migrations.AlterField(
            model_name='catalogofarticles',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='catalogofarticles',
            name='description_header',
            field=models.TextField(max_length=300, verbose_name='Description Header'),
        ),
        migrations.AlterField(
            model_name='catalogofarticles',
            name='keywords_header',
            field=models.TextField(max_length=300, verbose_name='Keywords Header'),
        ),
    ]
