# Generated by Django 5.0.4 on 2024-04-22 12:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_options_alter_catalogofarticles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_header',
            field=models.TextField(max_length=3000, verbose_name='Description Header'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=4000, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords_header',
            field=models.TextField(max_length=2000, verbose_name='Keywords Header'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=4000, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_catalog',
            field=models.CharField(max_length=4000, verbose_name='Title Catalog'),
        ),
    ]
