# Generated by Django 5.0.4 on 2024-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_catalogofarticles_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='catalog_name',
            field=models.CharField(max_length=100, verbose_name='Catalog Name'),
        ),
    ]
