# Generated by Django 5.0.4 on 2024-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog_slug_catalogofarticles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Moderation'),
        ),
    ]
