# Generated by Django 5.0.4 on 2024-04-29 09:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=6000, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=6000, verbose_name='Short Description'),
        ),
    ]
