# Generated by Django 5.0.4 on 2024-04-29 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blog_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Full Description'),
        ),
    ]
