# Generated by Django 4.2.11 on 2024-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_sitemap',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-02T00:00:00', verbose_name='Date Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogofarticles',
            name='date_sitemap',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-02T00:00:00', verbose_name='Date Added'),
            preserve_default=False,
        ),
    ]
